before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq phantomjs
install: 
  - cpanm --installdeps --with-develop --with-configure --notest .
  - mbtiny regenerate
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
